{
 "title": "Node Metrics",
 "description": "System Metrics on Nodes",
 "tags": [
  "pulsar",
  "node"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "node_time_seconds{instance=~\".+\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "System Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "System Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "node_time_seconds{instance=\"$instance\"} - node_boot_time_seconds{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Virtual CPUs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{mode=\"user\", instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "RAM available",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "(node_memory_MemAvailable_bytes{instance=\"$instance\"} or (node_memory_MemFree_bytes{instance=\"$instance\"} + node_memory_Buffers_bytes{instance=\"$instance\"} + node_memory_Cached_bytes{instance=\"$instance\"})) / node_memory_MemTotal_bytes{instance=\"$instance\"} * 100"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "sum(rate(node_cpu_seconds_total{instance=\"$instance\"}[$interval])) by (mode) * 100 / count(node_cpu_seconds_total{instance=\"$instance\"}) by (mode) or sum(irate(node_cpu_seconds_total{instance=\"$instance\"}[5m])) by (mode) * 100 / count(node_cpu_seconds_total{instance=\"$instance\"}) by (mode)",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "calculatedInterval": "10s",
     "expr": "node_load1{instance=\"$instance\"}",
     "legendFormat": "Load 1m"
    },
    {
     "calculatedInterval": "10s",
     "expr": "node_load5{instance=\"$instance\"}",
     "legendFormat": "Load 5m"
    },
    {
     "calculatedInterval": "10s",
     "expr": "node_load15{instance=\"$instance\"}",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "Page In/Page Out",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "calculatedInterval": "10s",
     "expr": "rate(node_vmstat_pgpgin{instance=\"$instance\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{instance=\"$instance\"}[5m]) * 1024",
     "legendFormat": "Page In"
    },
    {
     "calculatedInterval": "10s",
     "expr": "rate(node_vmstat_pgpgout{instance=\"$instance\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{instance=\"$instance\"}[5m]) * 1024",
     "legendFormat": "Page Out"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Forks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(node_forks_total{instance=\"$instance\"}[$interval]) or irate(node_forks_total{instance=\"$instance\"}[5m])",
       "legendFormat": "Forks"
      }
     ]
    },
    {
     "title": "Processes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "node_procs_running{instance=\"$instance\"}",
       "legendFormat": "Processes in runnable state"
      },
      {
       "calculatedInterval": "2m",
       "expr": "node_procs_blocked{instance=\"$instance\"}",
       "legendFormat": "Processes blocked waiting for I/O to complete"
      }
     ]
    },
    {
     "title": "Context Switches",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(node_context_switches_total{instance=\"$instance\"}[$interval]) or irate(node_context_switches_total{instance=\"$instance\"}[5m])",
       "legendFormat": "Context Switches"
      }
     ]
    },
    {
     "title": "Interrupts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(node_intr_total{instance=\"$instance\"}[$interval]) or irate(node_intr_total{instance=\"$instance\"}[5m])",
       "legendFormat": "Interrupts"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "node_memory_MemTotal_bytes{instance=\"$instance\"}",
       "legendFormat": "Total"
      },
      {
       "calculatedInterval": "2s",
       "expr": "node_memory_MemTotal_bytes{instance=\"$instance\"} - (node_memory_MemAvailable_bytes{instance=\"$instance\"} or (node_memory_MemFree_bytes{instance=\"$instance\"} + node_memory_Buffers_bytes{instance=\"$instance\"} + node_memory_Cached_bytes{instance=\"$instance\"}))",
       "legendFormat": "Used"
      },
      {
       "calculatedInterval": "2s",
       "expr": "node_memory_MemAvailable_bytes{instance=\"$instance\"} or (node_memory_MemFree_bytes{instance=\"$instance\"} + node_memory_Buffers_bytes{instance=\"$instance\"} + node_memory_Cached_bytes{instance=\"$instance\"})",
       "legendFormat": "Available"
      }
     ]
    },
    {
     "title": "Memory Distribution",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "node_memory_MemTotal_bytes{instance=\"$instance\"} - (node_memory_MemFree_bytes{instance=\"$instance\"} + node_memory_Buffers_bytes{instance=\"$instance\"} + node_memory_Cached_bytes{instance=\"$instance\"})",
       "legendFormat": "Used"
      },
      {
       "calculatedInterval": "2s",
       "expr": "node_memory_MemFree_bytes{instance=\"$instance\"}",
       "legendFormat": "Free"
      },
      {
       "calculatedInterval": "2s",
       "expr": "node_memory_Buffers_bytes{instance=\"$instance\"}",
       "legendFormat": "Buffers"
      },
      {
       "calculatedInterval": "2s",
       "expr": "node_memory_Cached_bytes{instance=\"$instance\"}",
       "legendFormat": "Cached"
      }
     ]
    }
   ]
  },
  {
   "title": "Swap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Swap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "node_memory_SwapTotal_bytes{instance=\"$instance\"} - node_memory_SwapFree_bytes{instance=\"$instance\"}",
       "legendFormat": "Used"
      },
      {
       "calculatedInterval": "2s",
       "expr": "node_memory_SwapFree_bytes{instance=\"$instance\"}",
       "legendFormat": "Free"
      }
     ]
    },
    {
     "title": "Swap Activity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "rate(node_vmstat_pswpin{instance=\"$instance\"}[$interval]) * 4096 or irate(node_vmstat_pswpin{instance=\"$instance\"}[5m]) * 4096",
       "legendFormat": "Swap In"
      },
      {
       "calculatedInterval": "2s",
       "expr": "rate(node_vmstat_pswpout{instance=\"$instance\"}[$interval]) * 4096 or irate(node_vmstat_pswpout{instance=\"$instance\"}[5m]) * 4096",
       "legendFormat": "Swap Out"
      }
     ]
    },
    {
     "title": "Mem Fault",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(node_vmstat_pgmajfault{instance=\"$instance\"}[1m])",
       "legendFormat": "major fault"
      },
      {
       "expr": "rate(node_vmstat_pgfault{instance=\"$instance\"}[1m])",
       "legendFormat": "minor fault"
      }
     ]
    },
    {
     "title": "Page/Swap in/out",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(node_vmstat_pgpgin{instance=\"$instance\"}[1m])",
       "legendFormat": "page in"
      },
      {
       "expr": "rate(node_vmstat_pgpgout{instance=\"$instance\"}[1m])",
       "legendFormat": "page out"
      },
      {
       "expr": "rate(node_vmstat_pswpout{instance=\"$instance\"}[1m])",
       "legendFormat": "swap out"
      },
      {
       "expr": "rate(node_vmstat_pswpin{instance=\"$instance\"}[1m])",
       "legendFormat": "swap in"
      }
     ]
    }
   ]
  },
  {
   "title": "I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "I/O Util",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "rate(node_disk_io_time_seconds_total{instance=\"$instance\"}[1m]) / 1000",
       "legendFormat": "{{ device }}",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemTotal%7Binstance%3D%5C%22%24host%5C%22%7D%20-%20(node_memory_MemFree%7Binstance%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Binstance%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Binstance%3D%5C%22%24host%5C%22%7D)%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
      }
     ]
    },
    {
     "title": "I/O in Progress",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "rate(node_disk_io_now{instance=\"$instance\"}[1m])",
       "legendFormat": "{{ device }}"
      }
     ]
    },
    {
     "title": "I/O Average Read Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "rate(node_disk_read_time_seconds_total{instance=\"$instance\"}[1m]) / 1000 / rate(node_disk_reads_completed_total{instance=\"$instance\"}[1m])",
       "legendFormat": "{{ device }}"
      }
     ]
    },
    {
     "title": "I/O Average Write Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "rate(node_disk_write_time_seconds_total{instance=\"$instance\"}[1m]) / 1000 / rate(node_disk_writes_completed_total{instance=\"$instance\"}[1m])",
       "legendFormat": "{{ device }}"
      }
     ]
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Allocated File Descriptor",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_filefd_allocated{instance=\"$instance\"}",
       "legendFormat": "Allocated File Descriptor"
      }
     ]
    },
    {
     "title": "Maximum File Descriptor",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_filefd_maximum{instance=\"$instance\"}",
       "legendFormat": "Maximum File Descriptor"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Network Traffic",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "rate(node_network_receive_bytes_total{instance=\"$instance\", device!=\"lo\"}[$interval]) or irate(node_network_receive_bytes_total{instance=\"$instance\", device!=\"lo\"}[5m]) ",
       "legendFormat": "Inbound: {{ device }}"
      },
      {
       "calculatedInterval": "2s",
       "expr": "rate(node_network_transmit_bytes_total{instance=\"$instance\", device!=\"lo\"}[$interval]) or irate(node_network_transmit_bytes_total{instance=\"$instance\", device!=\"lo\"}[5m])",
       "legendFormat": "Outbound: {{ device }}"
      }
     ]
    },
    {
     "title": "Network Utilization Hourly",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "sum(increase(node_network_receive_bytes_total{instance=\"$instance\", device!=\"lo\"}[1h]))",
       "legendFormat": "Received"
      },
      {
       "calculatedInterval": "2s",
       "expr": "sum(increase(node_network_transmit_bytes_total{instance=\"$instance\", device!=\"lo\"}[1h]))",
       "legendFormat": "Sent"
      }
     ]
    },
    {
     "title": "TCP In Use",
     "type": "timeseries",
     "description": "Number of TCP sockets in state inuse.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_sockstat_TCP_inuse{instance=\"$instance\"}",
       "legendFormat": "TCP In Use"
      }
     ]
    }
   ]
  }
 ]
}