{
 "title": "ZooKeeper by Prometheus",
 "description": "ZooKeeper Dashboard for Prometheus metrics scraper",
 "tags": [
  "pulsar",
  "zookeeper"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(znode_count{cluster=~\".+\"}, cluster)"
    }
   },
   {
    "name": "kubernetes_pod_name",
    "label": "zookeeper server",
    "query": {
     "query": "label_values(znode_count{cluster=~\"$cluster\", kubernetes_pod_name=~\".+\"}, kubernetes_pod_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overall",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "znode_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "znode_count{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
     "legendFormat": "{{kubernetes_pod_name}} znode_count"
    },
    {
     "expr": "ephemerals_count{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
     "legendFormat": "{{kubernetes_pod_name}} ephemerals"
    }
   ]
  },
  {
   "title": "znode_count_rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(znode_count{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[5m])",
     "legendFormat": "{{kubernetes_pod_name}} znode_count_rate"
    },
    {
     "expr": "rate(ephemerals_count{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[5m])",
     "legendFormat": "{{kubernetes_pod_name}} ephemerals_rate"
    }
   ]
  },
  {
   "title": "global_sessions",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "global_sessions{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "local_sessions ",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "local_sessions{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "write_per_namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(write_per_namespace_sum{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$__rate_interval])",
     "legendFormat": "{{kubernetes_pod_name}} write_per_namespace:{{key}}"
    }
   ]
  },
  {
   "title": "read_per_namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(read_per_namespace_sum{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$__rate_interval])",
     "legendFormat": "{{kubernetes_pod_name}} read_per_namespace:{{key}}"
    }
   ]
  },
  {
   "title": "approximate_data_size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "approximate_data_size{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
     "legendFormat": "{{kubernetes_pod_name}} approximate_data_size"
    }
   ]
  },
  {
   "title": "packets_received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(packets_received{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$__rate_interval])",
     "legendFormat": "{{kubernetes_pod_name}} packets_received"
    }
   ]
  },
  {
   "title": "packets_sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(packets_sent{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$__rate_interval])",
     "legendFormat": "{{kubernetes_pod_name}} packets_sent"
    }
   ]
  },
  {
   "title": "response_packet_cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "response_packet_cache_misses{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
     "legendFormat": "{{kubernetes_pod_name}} response_packet_cache_misses"
    },
    {
     "expr": "response_packet_cache_hits{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
     "legendFormat": "{{kubernetes_pod_name}} response_packet_cache_hits"
    },
    {
     "expr": "response_packet_get_children_cache_misses{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
     "legendFormat": "{{kubernetes_pod_name}} response_packet_get_children_cache_misses"
    },
    {
     "expr": "response_packet_get_children_cache_hits{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
     "legendFormat": "{{kubernetes_pod_name}} response_packet_get_children_cache_hits"
    }
   ]
  },
  {
   "title": "unrecoverable_error_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "unrecoverable_error_count{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
     "legendFormat": "{{kubernetes_pod_name}} unrecoverable_error_count"
    }
   ]
  },
  {
   "title": "digest_mismatches_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "digest_mismatches_count{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
     "legendFormat": "{{kubernetes_pod_name}} digest_mismatches_count"
    }
   ]
  },
  {
   "title": "startup_snap_load_time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "startup_snap_load_time_sum{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
     "legendFormat": "{{kubernetes_pod_name}} startup_snap_load_time"
    }
   ]
  },
  {
   "title": "startup_txns_loaded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "startup_txns_loaded_sum{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
     "legendFormat": "{{kubernetes_pod_name}} startup_txns_loaded"
    }
   ]
  },
  {
   "title": "db_init_time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "dbinittime_sum{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
     "legendFormat": "{{kubernetes_pod_name}} db_init_time"
    }
   ]
  },
  {
   "title": "Quorum/Leader Election",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "quorum_size",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(quorum_size{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"})",
       "legendFormat": "quorum_size"
      }
     ]
    },
    {
     "title": "leader",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "leader_uptime{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "leader_uptime",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "leader_uptime{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}} leader_uptime"
      }
     ]
    },
    {
     "title": "learner/observer",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "max(learners{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"})",
       "legendFormat": "learners"
      },
      {
       "expr": "max(synced_non_voting_followers{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"})",
       "legendFormat": "synced_non_voting_followers"
      },
      {
       "expr": "max(synced_observers{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"})",
       "legendFormat": "synced_observers"
      }
     ]
    },
    {
     "title": "election_time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "election_time_count{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}} election_time_count"
      },
      {
       "expr": "election_time_sum{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}} election_time_sum(ms)"
      },
      {
       "expr": "election_time_sum/election_time_count{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}} election_avg_time(ms)"
      }
     ]
    },
    {
     "title": "quorum uptime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "uptime{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}} uptime"
      }
     ]
    },
    {
     "title": "learner_commit_received_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "learner_commit_received_count{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}} learner_commit_received_count"
      }
     ]
    },
    {
     "title": "commit_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "commit_count{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}} commit_count"
      }
     ]
    },
    {
     "title": "snap_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "snap_count{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}} snap_count"
      }
     ]
    },
    {
     "title": "diff_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "diff_count{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}} diff_count"
      }
     ]
    },
    {
     "title": "looking_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "looking_count{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}} looking_count"
      }
     ]
    },
    {
     "title": "proposal_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "proposal_count{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}} proposal_count"
      }
     ]
    },
    {
     "title": "proposal_size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "last_proposal_size{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}} last_proposal_size"
      },
      {
       "expr": "max_proposal_size{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}} max_proposal_size"
      },
      {
       "expr": "min_proposal_size{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}} min_proposal_size"
      }
     ]
    },
    {
     "title": "follower_sync_time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(follower_sync_time_sum{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[1m])",
       "legendFormat": "{{kubernetes_pod_name}} follower_sync_time"
      }
     ]
    },
    {
     "title": "learner_handler_qp_size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "learner_handler_qp_size_sum{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}} learner_handler_qp_size_sum sid:{{key}}"
      }
     ]
    },
    {
     "title": "quit_leading_due_to_disloyal_voter",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "quit_leading_due_to_disloyal_voter{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}} quit_leading_due_to_disloyal_voter"
      }
     ]
    },
    {
     "title": "Observer Master",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(om_commit_process_time_ms_sum{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[5m])",
       "legendFormat": "{{kubernetes_pod_name}} om_commit_process_time"
      },
      {
       "expr": "rate(om_proposal_process_time_ms_sum{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[5m])",
       "legendFormat": "{{kubernetes_pod_name}} om_proposal_process_time"
      }
     ]
    }
   ]
  },
  {
   "title": "Session/Watch",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "watch_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "watch_count{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}} watch_count"
      }
     ]
    },
    {
     "title": "node_changed_watch_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_changed_watch_count_sum{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}} node_changed_watch_count"
      }
     ]
    },
    {
     "title": "node_children_watch_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_children_watch_count_sum{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}} node_children_watch_count"
      }
     ]
    },
    {
     "title": "node_deleted_watch_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_deleted_watch_count_sum{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}} node_deleted_watch_count"
      }
     ]
    },
    {
     "title": "node_created_watch_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_created_watch_count_sum{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}} node_created_watch_count"
      }
     ]
    },
    {
     "title": "revalidate_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "revalidate_count{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}} revalidate_count"
      }
     ]
    },
    {
     "title": "stale_sessions_expired",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "stale_sessions_expired{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}} stale_sessions_expired"
      }
     ]
    },
    {
     "title": "dead_watchers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "dead_watchers_cleared{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}} dead_watchers_cleared"
      },
      {
       "expr": "dead_watchers_queued{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}} dead_watchers_queued"
      },
      {
       "expr": "rate(dead_watchers_cleaner_latency_sum{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[5m])",
       "legendFormat": "{{kubernetes_pod_name}} dead_watchers_cleaner_latency"
      }
     ]
    },
    {
     "title": "add_dead_watcher_stall_time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "add_dead_watcher_stall_time{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}} add_dead_watcher_stall_time"
      }
     ]
    }
   ]
  },
  {
   "title": "Client/Connection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "outstanding_requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "outstanding_requests{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}} outstanding_requests"
      }
     ]
    },
    {
     "title": "client_response_size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "last_client_response_size{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}} last_client_response_size"
      },
      {
       "expr": "min_client_response_size{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}} min_client_response_size"
      },
      {
       "expr": "max_client_response_size{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}} max_client_response_size"
      }
     ]
    },
    {
     "title": "bytes_received_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "bytes_received_count{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}} bytes_received_count"
      }
     ]
    },
    {
     "title": "connection_request_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "connection_request_count{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}} connection_request_count"
      }
     ]
    },
    {
     "title": "num_alive_connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "num_alive_connections{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}} num_alive_connections"
      }
     ]
    },
    {
     "title": "connection_rejected",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "connection_rejected{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}} connection_rejected"
      }
     ]
    },
    {
     "title": "connection_drop_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "connection_drop_count{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}} connection_drop_count"
      }
     ]
    },
    {
     "title": "connection_drop_probability",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "connection_drop_probability{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}} connection_drop_probability"
      }
     ]
    },
    {
     "title": "sessionless_connections_expired",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sessionless_connections_expired{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}} sessionless_connections_expired"
      }
     ]
    },
    {
     "title": "connection_token_deficit",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(connection_token_deficit_sum{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[5m])",
       "legendFormat": "{{kubernetes_pod_name}} connection_token_deficit"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk/Snapshot",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "open_file_descriptor",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "open_file_descriptor_count{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "fsync_time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "fsynctime_sum * 1000 /fsynctime_count{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}} fsynctime_avg(μs)"
      },
      {
       "expr": "irate(fsynctime_sum{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[1m])",
       "legendFormat": "{{kubernetes_pod_name}} fsynctime_rate"
      }
     ]
    },
    {
     "title": "snapshot_time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(snapshottime_sum{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[5m])",
       "legendFormat": "{{kubernetes_pod_name}} snapshot_time_rate"
      }
     ]
    }
   ]
  },
  {
   "title": "Prep_Processor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "prep_process_time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(prep_process_time_sum{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[5m])",
       "legendFormat": "{{kubernetes_pod_name}} prep_process_time"
      }
     ]
    },
    {
     "title": "prep_processor_queue_time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(prep_processor_queue_time_ms_sum{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[5m])",
       "legendFormat": "{{kubernetes_pod_name}} prep_processor_queue_time_ms"
      }
     ]
    },
    {
     "title": "prep_processor_queue_size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(prep_processor_queue_size_sum{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[5m])",
       "legendFormat": "{{kubernetes_pod_name}} prep_processor_queue_size"
      }
     ]
    },
    {
     "title": "prep_processor_request_queued",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "prep_processor_request_queued{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}} prep_processor_request_queued"
      }
     ]
    },
    {
     "title": "outstanding_changes_queued",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "outstanding_changes_queued{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}} outstanding_changes_queued"
      },
      {
       "expr": "outstanding_changes_removed{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}} outstanding_changes_removed"
      }
     ]
    },
    {
     "title": "close_session_prep_time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(close_session_prep_time_sum{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[5m])",
       "legendFormat": "{{kubernetes_pod_name}} close_session_prep_time"
      }
     ]
    }
   ]
  },
  {
   "title": "Sync_Processor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "sync_process_time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(sync_process_time_sum{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[5m])",
       "legendFormat": "{{kubernetes_pod_name}} sync_process_time"
      }
     ]
    },
    {
     "title": "sync_processor_queue_flush_time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(sync_processor_queue_flush_time_ms_sum{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[5m])",
       "legendFormat": "{{kubernetes_pod_name}} sync_processor_queue_flush_time"
      }
     ]
    },
    {
     "title": "sync_processor_queue_size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(sync_processor_queue_size_sum{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[5m])",
       "legendFormat": "{{kubernetes_pod_name}} sync_processor_queue_size"
      }
     ]
    },
    {
     "title": "sync_processor_request_queued",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sync_processor_request_queued{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}} sync_processor_request_queued"
      }
     ]
    },
    {
     "title": "sync_processor_batch_size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(sync_processor_batch_size_sum{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[5m])",
       "legendFormat": "{{kubernetes_pod_name}} sync_processor_batch_size"
      }
     ]
    }
   ]
  },
  {
   "title": "Commit_Processor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "commit_process_time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(commit_process_time_sum{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[5m])",
       "legendFormat": "{{kubernetes_pod_name}} commit_process_time"
      },
      {
       "expr": "rate(read_commitproc_time_ms_sum{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[5m])",
       "legendFormat": "{{kubernetes_pod_name}} read_commitproc_time"
      },
      {
       "expr": "rate(write_commitproc_time_ms_sum{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[5m])",
       "legendFormat": "{{kubernetes_pod_name}} write_commitproc_time"
      }
     ]
    },
    {
     "title": "commit_proc_req_queued",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(write_commit_proc_req_queued_sum{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[5m])",
       "legendFormat": "{{kubernetes_pod_name}} write_commit_proc_req_queued"
      },
      {
       "expr": "rate(read_commit_proc_req_queued_sum{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[5m])",
       "legendFormat": "{{kubernetes_pod_name}} read_commit_proc_req_queued"
      },
      {
       "expr": "rate(commit_commit_proc_req_queued_sum{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[5m])",
       "legendFormat": "{{kubernetes_pod_name}} commit_commit_proc_req_queued"
      }
     ]
    },
    {
     "title": "requests_in_session_queue",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(requests_in_session_queue_sum{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[5m])",
       "legendFormat": "{{kubernetes_pod_name}} requests_in_session_queue"
      }
     ]
    },
    {
     "title": "commit_proc_issued",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(read_commit_proc_issued_sum{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[5m])",
       "legendFormat": "{{kubernetes_pod_name}} read_commit_proc_issued"
      },
      {
       "expr": "rate(write_commit_proc_issued_sum{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[5m])",
       "legendFormat": "{{kubernetes_pod_name}} write_commit_proc_issued"
      }
     ]
    },
    {
     "title": "concurrent_request_processing_in_commit_processor",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(concurrent_request_processing_in_commit_processor_sum{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[5m])",
       "legendFormat": "{{kubernetes_pod_name}} concurrent_request_processing_in_commit_processor"
      }
     ]
    },
    {
     "title": "time_waiting_empty_pool_in_commit_processor_read",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(time_waiting_empty_pool_in_commit_processor_read_ms_sum{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[5m])",
       "legendFormat": "{{kubernetes_pod_name}} time_waiting_empty_pool_in_commit_processor_read"
      }
     ]
    },
    {
     "title": "pending_session_queue_size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(pending_session_queue_size_sum{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[5m])",
       "legendFormat": "{{kubernetes_pod_name}} pending_session_queue_size"
      }
     ]
    },
    {
     "title": "local_write_committed_time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(local_write_committed_time_ms_sum{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[5m])",
       "legendFormat": "{{kubernetes_pod_name}} local_write_committed_time_ms"
      }
     ]
    },
    {
     "title": "server_write_committed_time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(server_write_committed_time_ms_sum{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[5m])",
       "legendFormat": "{{kubernetes_pod_name}} server_write_committed_time"
      }
     ]
    },
    {
     "title": "write_batch_time_in_commit_processor",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(write_batch_time_in_commit_processor_sum{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[5m])",
       "legendFormat": "{{kubernetes_pod_name}} write_batch_time_in_commit_processor"
      }
     ]
    },
    {
     "title": "reads_after_write_in_session_queue",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(reads_after_write_in_session_queue_sum{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[5m])",
       "legendFormat": "{{kubernetes_pod_name}} reads_after_write_in_session_queue"
      }
     ]
    },
    {
     "title": "session_queues_drained",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(session_queues_drained_sum{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[5m])",
       "legendFormat": "{{kubernetes_pod_name}} session_queues_drained"
      }
     ]
    },
    {
     "title": "reads_issued_from_session_queue",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(reads_issued_from_session_queue_sum{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[5m])",
       "legendFormat": "{{kubernetes_pod_name}} reads_issued_from_session_queue"
      }
     ]
    },
    {
     "title": "request_commit_queued",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "request_commit_queued{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}} request_commit_queued"
      }
     ]
    }
   ]
  },
  {
   "title": "Final_Processor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "write_final_proc_time_ms",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(write_final_proc_time_ms_sum{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[5m])",
       "legendFormat": "{{kubernetes_pod_name}} write_final_proc_time_ms"
      }
     ]
    },
    {
     "title": "read_final_proc_time_ms",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(read_final_proc_time_ms_sum{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[5m])",
       "legendFormat": "{{kubernetes_pod_name}} read_final_proc_time_ms"
      }
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "read_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(readlatency_sum{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[5m])",
       "legendFormat": "{{kubernetes_pod_name}} readlatency"
      }
     ]
    },
    {
     "title": "update_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(updatelatency_sum{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[5m])",
       "legendFormat": "{{kubernetes_pod_name}} updatelatency"
      }
     ]
    },
    {
     "title": "max_min_avg_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "max_latency{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}} max_latency"
      },
      {
       "expr": "min_latency{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}} min_latency"
      },
      {
       "expr": "avg_latency{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}} avg_latency"
      }
     ]
    },
    {
     "title": "proposal_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(proposal_latency_sum{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[5m])",
       "legendFormat": "{{kubernetes_pod_name}} proposal_latency"
      }
     ]
    },
    {
     "title": "quorum_ack_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(quorum_ack_latency_sum{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[5m])",
       "legendFormat": "{{kubernetes_pod_name}} quorum_ack_latency"
      }
     ]
    },
    {
     "title": "ack_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(ack_latency_sum{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[5m])",
       "legendFormat": "{{kubernetes_pod_name}} ack_latency_sum"
      }
     ]
    },
    {
     "title": "propagation_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(propagation_latency_sum{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[5m])",
       "legendFormat": "{{kubernetes_pod_name}} propagation_latency"
      }
     ]
    },
    {
     "title": "commit_propagation_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(commit_propagation_latency_sum{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[5m])",
       "legendFormat": "{{kubernetes_pod_name}} commit_propagation_latency"
      }
     ]
    },
    {
     "title": "proposal_ack_creation_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "proposal_ack_creation_latency{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}} proposal_ack_creation_latency-{{quantile}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Security",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "tls_handshake",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "tls_handshake_exceeded{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}} tls_handshake_exceeded"
      },
      {
       "expr": "outstanding_tls_handshake{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}} outstanding_tls_handshake"
      }
     ]
    },
    {
     "title": "ensemble_auth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ensemble_auth_fail{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}} ensemble_auth_fail"
      },
      {
       "expr": "ensemble_auth_success{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}} ensemble_auth_success"
      },
      {
       "expr": "ensemble_auth_skip{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}} ensemble_auth_skip"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "jvm_classes_loaded",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(jvm_classes_loaded{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"})"
      }
     ]
    },
    {
     "title": "jvm_threads_current",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(jvm_threads_current{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"})"
      }
     ]
    },
    {
     "title": "jvm_threads_deadlocked",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(jvm_threads_deadlocked{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"})"
      }
     ]
    },
    {
     "title": "jvm_pause_time_ms",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(jvm_pause_time_ms_sum{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[5m])",
       "legendFormat": "{{kubernetes_pod_name}} jvm_pause_time_ms"
      }
     ]
    },
    {
     "title": "jvm_gc_collection_seconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(jvm_gc_collection_seconds_sum{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[5m])",
       "legendFormat": "{{kubernetes_pod_name}} gc:{{gc}}"
      }
     ]
    },
    {
     "title": "jvm_threads_state",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_threads_state{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}} state:{{state}}"
      }
     ]
    },
    {
     "title": "jvm_memory_pool_bytes_used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_pool_bytes_used{cluster=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "{{kubernetes_pod_name}} pool:{{pool}}"
      }
     ]
    }
   ]
  }
 ]
}