apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  repo: https://charts.jetstack.io
  chart: cert-manager
  version: v1.6.0
  targetNamespace: cert-manager
  valuesContent: |-
    installCRDs: "true"
    extraArgs:
      - "--enable-certificate-owner-ref=true"
