apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources/pulsar.yaml
- resources/issuer.yaml

secretGenerator:
- name: ca-key-pair
  options:
    # Kustomize can't replace generator name in Issuer, so we need to disable it
    disableNameSuffixHash: true
  files:
  - tls.crt=./ca.crt
  - tls.key=./ca.key
  type: "kubernetes.io/tls"
- name: gdcn-license-key
  options:
    disableNameSuffixHash: true
  envs:
  - ./gooddata-license.env

namespace: gooddata
