{
 "title": "Calcique",
 "tags": [ "tiger" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_container_info, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{application=\"calcique\", namespace=\"$namespace\"}, pod)"
    }
   },
   {
    "name": "interval",
    "query": "1m,2m,3m,5m,10m,30m,1h,6h,12h,1d"
   },
   { "name": "application", "query": "calcique" }
  ]
 },
 "panels": [
  { "title": "About", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "<p>This dashboards sums up useful information about the Calcique service, which is responsible for translating report computation requests to SQL.</p>\n"
   }
  },
  { "title": "MAQL Processing Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "MAQL Processing Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(max_over_time(calcique_maql_interpret_seconds_max{application=\"$application\",namespace=\"$namespace\",pod=~\"$pod\"}[$interval]))",
     "legendFormat": "interpret {{pod}}"
    },
    {
     "expr": "max(max_over_time(calcique_maql_optimize_seconds_max{application=\"$application\",namespace=\"$namespace\",pod=~\"$pod\"}[$interval]))",
     "legendFormat": "optimize {{pod}}"
    },
    {
     "expr": "max(max_over_time(calcique_maql_generate_seconds_max{application=\"$application\",namespace=\"$namespace\",pod=~\"$pod\"}[$interval]))",
     "legendFormat": "generate {{pod}}"
    }
   ]
  },
  {
   "title": "Metadata Query Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(max_over_time(calcique_metadata_seconds_max{application=\"$application\",namespace=\"$namespace\",pod=~\"$pod\"}[$interval])) by (source)",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Log Events",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum(increase(log4j2_events_total{application=\"$application\", namespace=\"$namespace\", pod=~\"$pod\"}[$interval])) by (level)",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Pulsar Compute Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(calcique_compute_seconds_count{application=\"$application\",namespace=\"$namespace\",pod=~\"$pod\"}[$interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Max Request Duration per Interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max_over_time(calcique_compute_seconds_max{application=\"$application\",namespace=\"$namespace\",pod=~\"$pod\"}[$interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pulsar Compute Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum(increase(calcique_compute_errors_total{application=\"$application\", namespace=\"$namespace\"}[$interval]))",
     "legendFormat": "sum of compute errors"
    }
   ]
  },
  { "title": "GRPC Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "GRPC Compute Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_processing_duration_seconds_count{application=\"$application\",namespace=\"$namespace\",pod=~\"$pod\", service=\"tiger.CalciqueService\", method=\"compute\"}[$interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GRPC ValidObjects Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_processing_duration_seconds_count{application=\"$application\",namespace=\"$namespace\",pod=~\"$pod\", service=\"tiger.CalciqueService\", method=\"validObjects\"}[$interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GRPC LabelElements Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_processing_duration_seconds_count{application=\"$application\",namespace=\"$namespace\",pod=~\"$pod\", service=\"tiger.CalciqueService\", method=\"labelElements\"}[$interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GRPC Explain Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_processing_duration_seconds_count{application=\"$application\",namespace=\"$namespace\",pod=~\"$pod\", service=\"tiger.CalciqueService\", method=\"explain\"}[$interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GRPC Compute Error Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_processing_duration_seconds_count{application=\"$application\",namespace=\"$namespace\",pod=~\"$pod\", service=\"tiger.CalciqueService\", method=\"compute\", statusCode!=\"OK\"}[$interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GRPC Valid Objects Error Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 36 },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_processing_duration_seconds_count{application=\"$application\",namespace=\"$namespace\",pod=~\"$pod\", service=\"tiger.CalciqueService\", method=\"validObjects\", statusCode!=\"OK\"}[$interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GRPC Label Elements Error Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_processing_duration_seconds_count{application=\"$application\",namespace=\"$namespace\",pod=~\"$pod\", service=\"tiger.CalciqueService\", method=\"labelElements\", statusCode!=\"OK\"}[$interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GRPC Explain Error Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 36 },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_processing_duration_seconds_count{application=\"$application\",namespace=\"$namespace\",pod=~\"$pod\", service=\"tiger.CalciqueService\", method=\"explain\", statusCode!=\"OK\"}[$interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Max GRPC Compute Request Duration per Interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max_over_time(grpc_server_processing_duration_seconds_max{application=\"$application\",namespace=\"$namespace\",pod=~\"$pod\", service=\"tiger.CalciqueService\", method=\"compute\"}[$interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Max GRPC ValidObjects Request Duration per Interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max_over_time(grpc_server_processing_duration_seconds_max{application=\"$application\",namespace=\"$namespace\",pod=~\"$pod\", service=\"tiger.CalciqueService\", method=\"validObjects\"}[$interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Max GRPC LabelElements Request Duration per Interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max_over_time(grpc_server_processing_duration_seconds_max{application=\"$application\",namespace=\"$namespace\",pod=~\"$pod\", service=\"tiger.CalciqueService\", method=\"labelElements\"}[$interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Max GRPC explain Request Duration per Interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max_over_time(grpc_server_processing_duration_seconds_max{application=\"$application\",namespace=\"$namespace\",pod=~\"$pod\", service=\"tiger.CalciqueService\", method=\"explain\"}[$interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "system_cpu_usage{application=\"$application\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "system {{pod}}"
    },
    {
     "expr": "process_cpu_usage{application=\"$application\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "process {{pod}}"
    },
    {
     "expr": "avg_over_time(process_cpu_usage{application=\"$application\", namespace=\"$namespace\", pod=~\"$pod\"}[1h])",
     "legendFormat": "process-1h {{pod}}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_load_average_1m{application=\"$application\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "system-1m {{pod}}"
    },
    {
     "expr": "system_cpu_count{application=\"$application\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "cpus {{pod}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_live_threads{application=\"$application\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "live {{pod}}"
    },
    {
     "expr": "jvm_threads_daemon_threads{application=\"$application\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "daemon {{pod}}"
    },
    {
     "expr": "jvm_threads_peak_threads{application=\"$application\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "peak {{pod}}"
    },
    {
     "expr": "process_threads{application=\"$application\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "process {{pod}}"
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_states_threads{application=\"$application\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{state}} {{pod}}"
    }
   ]
  },
  { "title": "Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "JVM Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", pod=~\"$pod\", area=\"heap\"}) by (pod)",
     "legendFormat": "used {{pod}}"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{application=\"$application\", pod=~\"$pod\", area=\"heap\"}) by (pod)",
     "legendFormat": "committed {{pod}}"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{application=\"$application\", pod=~\"$pod\", area=\"heap\"}) by (pod)",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 61 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", pod=~\"$pod\", area=\"nonheap\"}) by (pod)",
     "legendFormat": "used {{pod}}"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{application=\"$application\", pod=~\"$pod\", area=\"nonheap\"}) by (pod)",
     "legendFormat": "committed {{pod}}"
    }
   ]
  },
  {
   "title": "JVM Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "used {{pod}}"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{application=\"$application\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "committed {{pod}}"
    }
   ]
  },
  {
   "title": "JVM Process Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 61 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_rss{namespace=\"$namespace\", container=\"$application\", pod=~\"$pod\"} ",
     "legendFormat": "rss {{pod}}"
    },
    {
     "expr": "container_memory_swap{namespace=\"$namespace\", container=\"$application\", pod=~\"$pod\"}",
     "legendFormat": "swap {{pod}}"
    },
    {
     "expr": "container_memory_rss{namespace=\"$namespace\", container=\"$application\", pod=~\"$pod\"} + container_memory_swap{namespace=\"$namespace\", container=\"$application\", pod=~\"$pod\"}",
     "legendFormat": "total {{pod}}"
    },
    {
     "expr": "kube_pod_container_resource_requests{resource=\"memory\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$application\"}",
     "legendFormat": "requests {{pod}}"
    },
    {
     "expr": "kube_pod_container_resource_limits{resource=\"memory\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$application\"}",
     "legendFormat": "limit {{pod}}"
    },
    {
     "expr": "sum((container_memory_rss{namespace=\"$namespace\", container=\"$application\", pod=~\"$pod\"} + container_memory_swap{namespace=\"$namespace\", container=\"$application\", pod=~\"$pod\"})) by (pod) - \nsum(jvm_memory_committed_bytes{application=\"$application\", pod=~\"$pod\"}) by (pod) - sum(jvm_buffer_memory_used_bytes{application=\"$application\", pod=~\"$pod\", id=\"direct\"}) by (pod)",
     "legendFormat": "unknown {{pod}}"
    }
   ]
  }
 ]
}