{
 "title": "PostgreSQL Exporter",
 "description": "postgres exporter Dashboard for display important postgreSQL metric",
 "tags": [
  "prometheus",
  "postgresql"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(pg_up, namespace)" } },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(pg_up{namespace=\"$namespace\"}, pod)"
    }
   },
   {
    "name": "Database",
    "query": {
     "query": "label_values({namespace=\"$namespace\"}, datname)"
    }
   },
   { "name": "Interval", "query": "30sec,1m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Global Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "PostgreSQL Version",
   "type": "stat",
   "description": "Source: server_version_num",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg_settings_server_version_num{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Max Replication Lag",
   "type": "stat",
   "description": "Max Replication lag behind master in seconds\n\nOnly available on a standby system.\n\nSource: pg_last_xact_replay_timestamp\n\nUse: pg_stat_replication for Details.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(pg_replication_lag{pod=\"$pod\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Active clients",
   "type": "stat",
   "description": "Clients executing Statements.\n\nSource: pg_stat_activity",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{state=\"active\",pod=\"$pod\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Shared Buffer Hits",
   "type": "gauge",
   "description": "Shared buffer hits vs reads from disc",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_blks_hit{pod=~\"$pod\", namespace=\"$namespace\"})/(sum(pg_stat_database_blks_hit{pod=~\"$pod\", namespace=\"$namespace\"})+sum(pg_stat_database_blks_read{pod=~\"$pod\", namespace=\"$namespace\"}))*100"
    }
   ]
  },
  {
   "title": "Connections used",
   "type": "gauge",
   "description": "Percentage of max_connections used",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_numbackends{namespace=\"$namespace\"})/max(pg_settings_max_connections{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Commit Ratio",
   "type": "gauge",
   "description": "Transaction committed vs rollbacked",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_xact_commit{pod=\"$pod\", namespace=\"$namespace\"})/(sum(pg_stat_database_xact_commit{pod=\"$pod\", namespace=\"$namespace\"}) + sum(pg_stat_database_xact_rollback{pod=\"$pod\", namespace=\"$namespace\"}))"
    }
   ]
  },
  {
   "title": "PostgreSQL Uptime",
   "type": "stat",
   "description": "Source: pg_postmaster_start_time()",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-(pg_postmaster_start_time_seconds{pod=\"$pod\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Transaction rate",
   "type": "stat",
   "description": "Transactions committed + roolback per minute\n\nSource: pg_stat_database,xact_commit + xact_rollback",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((rate(pg_stat_database_xact_commit{pod=\"$pod\", namespace=\"$namespace\"}[$Interval])))+sum((rate(pg_stat_database_xact_rollback{pod=\"$pod\", namespace=\"$namespace\"}[$Interval])))"
    }
   ]
  },
  {
   "title": "Query rate",
   "type": "stat",
   "description": "Statements executed per Minute.\nSource: pg_stat_statements.calls\nNeeds to be enabled separately due to potential performance cost.",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_statements_calls{pod=\"$pod\", namespace=\"$namespace\"}[$Interval]))"
    }
   ]
  },
  {
   "title": "Total database size",
   "type": "stat",
   "description": "Size of all databases in $Instance.\nSource: pg_database_size()\n\nNeeds to be enabled separately due to potential performance cost.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_database_size{pod=\"$pod\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Average query runtime",
   "type": "stat",
   "description": "Source: pg_stat_statements.total_time / pg_stat_statements.calls\nNeeds to be enabled separately due to potential performance cost.",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((delta(pg_stat_statements_total_time_seconds{pod=\"$pod\", namespace=\"$namespace\"}[$Interval])))/sum((delta(pg_stat_statements_calls{pod=\"$pod\", namespace=\"$namespace\"}[$Interval])))"
    }
   ]
  },
  {
   "title": "Shared Buffers",
   "type": "stat",
   "description": "Setting: shared_buffers in PostgreSQL.conf",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_shared_buffers_bytes{pod=\"$pod\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Max Connections",
   "type": "stat",
   "description": "Setting: max_connections in postgreSQL.conf",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_connections{pod=\"$pod\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Connections by state (stacked)",
   "type": "timeseries",
   "description": "View: pg_stat_activity",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (state) (pg_stat_activity_count{pod=\"$pod\", namespace=\"$namespace\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Connections by database (stacked)",
   "type": "timeseries",
   "description": "View: pg_stat_activity",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (datname) (pg_stat_activity_count{pod=\"$pod\", namespace=\"$namespace\"})",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "description": "1 Minute rate of transactions committed or rollback.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum ((rate(pg_stat_database_xact_commit{namespace=\"$namespace\"}[$Interval])))",
     "legendFormat": "committed"
    },
    {
     "expr": "sum ((rate(pg_stat_database_xact_rollback{namespace=\"$namespace\"}[$Interval])))",
     "legendFormat": "rollback"
    }
   ]
  },
  {
   "title": "Tuples inserts/updates/deletes",
   "type": "timeseries",
   "description": "Source: pg_stat_database",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum((rate(pg_stat_database_tup_inserted{pod=\"$pod\", namespace=\"$namespace\"}[$Interval])))",
     "legendFormat": "Inserts"
    },
    {
     "expr": "sum((rate(pg_stat_database_tup_updated{pod=\"$pod\", namespace=\"$namespace\"}[$Interval])))",
     "legendFormat": "Updates"
    },
    {
     "expr": "sum((rate(pg_stat_database_tup_deleted{pod=\"$pod\", namespace=\"$namespace\"}[$Interval])))",
     "legendFormat": "Deletes"
    }
   ]
  },
  {
   "title": "I/O Read/Write time",
   "type": "timeseries",
   "description": "* blk_read_time: Time spent reading data file blocks by backends in this database, in milliseconds\n* blk_write_time: Time spent writing data file blocks by backends in this database, in milliseconds\n\ntrack_io_timings needs to be activated",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum ((rate(pg_stat_database_blk_read_time{pod=\"$pod\", namespace=\"$namespace\"}[$Interval])))",
     "legendFormat": "blk_read_time"
    },
    {
     "expr": "sum ((rate(pg_stat_database_blk_write_time{pod=\"$pod\", namespace=\"$namespace\"}[$Interval])))",
     "legendFormat": "blk_read_time"
    }
   ]
  },
  {
   "title": "Tuples fetched/returned",
   "type": "timeseries",
   "description": "Source: pg_stat_database\n\n* tup_fetched: rows needed to satisfy queries\n* tup_returned: rows read/scanned",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum((rate(pg_stat_database_tup_fetched{pod=\"$pod\", namespace=\"$namespace\"}[$Interval])))",
     "legendFormat": "Fetched"
    },
    {
     "expr": "sum((rate(pg_stat_database_tup_returned{pod=\"$pod\", namespace=\"$namespace\"}[$Interval])))",
     "legendFormat": "Returned"
    }
   ]
  },
  {
   "title": "Locks by state",
   "type": "timeseries",
   "description": "Source: pg_locks",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (mode) (pg_locks_count{pod=\"$pod\", namespace=\"$namespace\"})",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Deadlocks by database",
   "type": "timeseries",
   "description": "Should be 0 \n\nSource: pg_stat_database\n\nWith log_lock_waits turned on, deadlocks will be logged to the PostgreSQL Logfiles.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (datname) ((rate(pg_stat_database_deadlocks{pod=\"$pod\", namespace=\"$namespace\"}[$Interval])))",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Temporary files by database",
   "type": "timeseries",
   "description": "Should be 0. If temporary files are created, it can indicate insufficient work_mem. With log_temp_files the creation of temporary files are logged to the PostgreSQL Logfiles.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (datname) ((rate(pg_stat_database_temp_files{pod=\"$pod\", namespace=\"$namespace\"}[$Interval])))",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Database: $Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "repeat": "Database",
   "targets": [
    {}
   ]
  },
  {
   "title": "Active clients",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (pg_stat_activity_count{state=\"active\",pod=\"$pod\", namespace=\"$namespace\",datname=~\"$Database\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Database size",
   "type": "stat",
   "description": "Needs to be enabled separately due to potential performance cost.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_database_size{pod=\"$pod\", namespace=\"$namespace\",datname=\"$Database\"}"
    }
   ]
  },
  {
   "title": "Shared Buffer Hits",
   "type": "gauge",
   "description": "Shared buffer hits vs reads from disc",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_database_blks_hit{pod=~\"$pod\", namespace=\"$namespace\",datname=~\"$Database\"}/(pg_stat_database_blks_hit{pod=~\"$pod\", namespace=\"$namespace\",datname=~\"$Database\"}+pg_stat_database_blks_read{pod=~\"$pod\", namespace=\"$namespace\",datname=~\"$Database\"})"
    }
   ]
  },
  {
   "title": "Commit Ratio",
   "type": "gauge",
   "description": "Transaction committed vs rollbacked",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_database_xact_commit{pod=\"$pod\", namespace=\"$namespace\",datname=~\"$Database\"}/(pg_stat_database_xact_commit{pod=\"$pod\", namespace=\"$namespace\",datname=~\"$Database\"} + pg_stat_database_xact_rollback{pod=\"$pod\", namespace=\"$namespace\",datname=~\"$Database\"})"
    }
   ]
  },
  {
   "title": "Transaction rate",
   "type": "stat",
   "description": "Transactions committed + roolback per minute\n\nSource: pg_stat_database,xact_commit + xact_rollback",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((rate(pg_stat_database_xact_commit{pod=\"$pod\", namespace=\"$namespace\",datname=\"$Database\"}[$Interval])))+sum((rate(pg_stat_database_xact_rollback{pod=\"$pod\", namespace=\"$namespace\",datname=\"$Database\"}[$Interval])))"
    }
   ]
  },
  {
   "title": "Connections by state (stacked)",
   "type": "timeseries",
   "description": "View: pg_stat_activity",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (state) (pg_stat_activity_count{pod=\"$pod\", namespace=\"$namespace\",datname=\"$Database\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "description": "1 Minute rate of transactions committed or rollback.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{pod=\"$pod\", namespace=\"$namespace\",datname=\"$Database\"}[$Interval])",
     "legendFormat": "committed"
    },
    {
     "expr": "rate(pg_stat_database_xact_rollback{pod=\"$pod\", namespace=\"$namespace\",datname=\"$Database\"}[$Interval])",
     "legendFormat": "rollback"
    }
   ]
  },
  {
   "title": "Tuples inserts/updates/deletes",
   "type": "timeseries",
   "description": "Source: pg_stat_database",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_inserted{pod=\"$pod\", namespace=\"$namespace\",datname=\"$Database\"}[$Interval])",
     "legendFormat": "Inserts"
    },
    {
     "expr": "rate(pg_stat_database_tup_updated{pod=\"$pod\", namespace=\"$namespace\",datname=\"$Database\"}[$Interval])",
     "legendFormat": "Updates"
    },
    {
     "expr": "rate(pg_stat_database_tup_deleted{pod=\"$pod\", namespace=\"$namespace\",datname=\"$Database\"}[$Interval])",
     "legendFormat": "Deletes"
    }
   ]
  },
  {
   "title": "Tuples fetched/returned",
   "type": "timeseries",
   "description": "Source: pg_stat_database\n\n* tup_fetched: rows needed to satisfy queries\n* tup_returned: rows read/scanned",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_fetched{pod=\"$pod\", namespace=\"$namespace\",datname=\"$Database\"}[$Interval])",
     "legendFormat": "Fetched"
    },
    {
     "expr": "rate(pg_stat_database_tup_returned{pod=\"$pod\", namespace=\"$namespace\",datname=\"$Database\"}[$Interval])",
     "legendFormat": "Returned"
    }
   ]
  },
  {
   "title": "Locks by state",
   "type": "timeseries",
   "description": "Source: pg_locks",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (mode) (pg_locks_count{pod=\"$pod\", namespace=\"$namespace\",datname=\"$Database\"})",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Deadlocks by database",
   "type": "timeseries",
   "description": "Should be 0 \n\nSource: pg_stat_database\n\nWith log_lock_waits turned on, deadlocks will be logged to the PostgreSQL Logfiles.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_deadlocks{pod=\"$pod\", namespace=\"$namespace\",datname=\"$Database\"}[$Interval])",
     "legendFormat": "deadlocks"
    }
   ]
  },
  {
   "title": "Temporary files by database",
   "type": "timeseries",
   "description": "Should be 0. If temporary files are created, it can indicate insufficient work_mem. With log_temp_files the creation of temporary files are logged to the PostgreSQL Logfiles.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_temp_files{pod=\"$pod\", namespace=\"$namespace\",datname=\"$Database\"}[$Interval])",
     "legendFormat": "temp_files"
    }
   ]
  }
 ]
}