{
 "title": "Redis overview",
 "tags": [
  "redis",
  "prometheus"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(redis_up, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Availability",
   "type": "text",
   "gridPos": { "h": 1, "w": 4, "x": 0, "y": 0 },
   "options": { "content": "\n\n\n\n" },
   "targets": [
    {}
   ]
  },
  {
   "title": "Resources usage",
   "type": "text",
   "gridPos": { "h": 1, "w": 8, "x": 4, "y": 0 },
   "options": { "content": "\n\n\n\n" },
   "targets": [
    {}
   ]
  },
  {
   "title": "Persistence",
   "type": "text",
   "gridPos": { "h": 1, "w": 4, "x": 12, "y": 0 },
   "options": { "content": "\n\n\n\n" },
   "targets": [
    {}
   ]
  },
  {
   "title": "Mem. cache",
   "type": "text",
   "gridPos": { "h": 1, "w": 4, "x": 16, "y": 0 },
   "options": { "content": "\n\n\n\n" },
   "targets": [
    {}
   ]
  },
  {
   "title": "Publisher-Subscriber",
   "type": "text",
   "gridPos": { "h": 1, "w": 4, "x": 20, "y": 0 },
   "options": { "content": "\n\n\n\n" },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "redis_uptime_in_seconds{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Memory Usage (if max memory)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 * (redis_memory_used_bytes{instance=\"$instance\"} / redis_memory_max_bytes{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Fragmentation Ratio",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "redis_mem_fragmentation_ratio{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Time since last save",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time() - redis_rdb_last_save_timestamp_seconds{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Hit percentage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 * rate(redis_keyspace_hits_total{instance=\"$instance\"}[5m]) / (rate(redis_keyspace_misses_total{instance=\"$instance\"}[5m]) + rate(redis_keyspace_hits_total{instance=\"$instance\"}[5m]))"
    }
   ]
  },
  {
   "title": "PubSub Channels",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "redis_pubsub_channels{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Connected slaves",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "redis_connected_slaves{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Conns Usage (if max clients defined)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 * (redis_connected_clients{instance=\"$instance\"} / redis_config_maxclients{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Changes since last save",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "redis_rdb_changes_since_last_save{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Eviction percentage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 * sum(rate(redis_evicted_keys_total{instance=\"$instance\"}[5m]) ) / sum(redis_db_keys{instance=\"$instance\"}) "
    }
   ]
  },
  {
   "title": "PubSub Patterns",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "redis_pubsub_patterns{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "redis_memory_used_bytes{instance=\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "redis_memory_max_bytes{instance=\"$instance\"}",
     "legendFormat": "Max Capacity"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "redis_memory_used_dataset_bytes{instance=\"$instance\"}",
     "legendFormat": "Datasets"
    },
    {
     "expr": "redis_memory_used_lua_bytes{instance=\"$instance\"}",
     "legendFormat": "Lua scripts"
    },
    {
     "expr": "redis_memory_used_overhead_bytes{instance=\"$instance\"}",
     "legendFormat": "Overhead"
    },
    {
     "expr": "redis_memory_used_scripts_bytes{instance=\"$instance\"}",
     "legendFormat": "Scripts"
    }
   ]
  },
  {
   "title": "Memory fragmentation ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "redis_mem_fragmentation_ratio{instance=\"$instance\"}",
     "legendFormat": "Ratio"
    }
   ]
  },
  {
   "title": "Connections usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "redis_connected_clients{instance=\"$instance\"}",
     "legendFormat": "Clients"
    },
    {
     "expr": "redis_config_maxclients{instance=\"$instance\"}",
     "legendFormat": "Max Clients"
    }
   ]
  },
  {
   "title": "Blocked and Rejected clients",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "redis_blocked_clients{instance=\"$instance\"}",
     "legendFormat": "Blocked"
    },
    {
     "expr": "rate(redis_rejected_connections_total{instance=\"$instance\"}[5m])",
     "legendFormat": "Rejected"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_commands_duration_seconds_total{instance=\"$instance\"}[5m])) / sum(rate(redis_commands_processed_total{instance=\"$instance\"}[5m]))",
     "legendFormat": "Response Time"
    }
   ]
  },
  {
   "title": "Slowlog increment",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(redis_slowlog_length{instance=\"$instance\"}[5m])",
     "legendFormat": "Response Time"
    }
   ]
  },
  {
   "title": "Keys / DB",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "redis_db_keys{instance=\"$instance\"}",
     "legendFormat": "{{db}}"
    }
   ]
  },
  {
   "title": "Average TTL",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "redis_db_avg_ttl_seconds{instance=\"$instance\"}",
     "legendFormat": "{{db}}"
    }
   ]
  },
  {
   "title": "Expired / Evicted keys",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(redis_expired_keys_total{instance=\"$instance\"}[5m])",
     "legendFormat": "Expired"
    },
    {
     "expr": "rate(redis_evicted_keys_total{instance=\"$instance\"}[5m])",
     "legendFormat": "Evicted"
    }
   ]
  },
  {
   "title": "Hit Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * rate(redis_keyspace_hits_total{instance=\"$instance\"}[5m]) / (rate(redis_keyspace_misses_total{instance=\"$instance\"}[5m]) + rate(redis_keyspace_hits_total{instance=\"$instance\"}[5m])) ",
     "legendFormat": "Hit"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * (rate(redis_cpu_sys_children_seconds_total{instance=\"$instance\"}[5m]) + rate(redis_cpu_sys_seconds_total{instance=\"$instance\"}[5m]))",
     "legendFormat": "System"
    },
    {
     "expr": "100 * (rate(redis_cpu_user_children_seconds_total{instance=\"$instance\"}[5m]) + rate(redis_cpu_user_seconds_total{instance=\"$instance\"}[5m]))",
     "legendFormat": "User"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 33 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "topk(5, irate(redis_commands_total{instance=\"$instance\"} [5m]))",
     "legendFormat": "{{cmd}}"
    }
   ]
  },
  {
   "title": "Network Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(redis_net_input_bytes_total{instance=\"$instance\"}[5m])",
     "legendFormat": "Inbound"
    },
    {
     "expr": "rate(redis_net_output_bytes_total{instance=\"$instance\"}[5m])",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "Conns/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(redis_connections_received_total{instance=\"$instance\"}[5m]) ",
     "legendFormat": "Inbound"
    }
   ]
  },
  {
   "title": "File descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "process_max_fds{instance=\"${instance}\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "process_open_fds{instance=\"${instance}\"}",
     "legendFormat": "Used"
    }
   ]
  }
 ]
}